### ISSUE TITLE
[FRONTEND] About page

### ISSUE THREAD

**Issue by hkrishna** [i8ramin/karlandkeke#10]
A static page that has basic information about this project and how people can get involved etc..

**Comment by tarekp** [comment]
@hkrishna I just assigned myself to this task.

**Comment by tarekp** [comment]
Draft complete. Awaiting final feedback.

**Comment by hkrishna** [comment]
@tarekp can you attach the draft here please? thank you!

**Comment by tarekp** [comment]
![karl keke_about](https://cloud.githubusercontent.com/assets/471852/12079365/4999ccb2-b21d-11e5-93fc-174c3a797d9c.jpg)

**Comment by tarekp** [comment]
Uploaded in Slack since git doesn't allow for .ai files

**Comment by hkrishna** [comment]
this is in master now. looks good! closing this issue
