### ISSUE TITLE
[FRONTEND] Search in the topnav

### ISSUE THREAD

**Issue by hkrishna** [i8ramin/karlandkeke#7]
* [x] Search by daycare
* [x] Search by location (@tarekp we might need some product/design around this - is the user typing out neighborhoods/ cities/ boroughs? this might be a v2 feature? )
 
![topnav](https://cloud.githubusercontent.com/assets/840737/11945790/95986ff2-a821-11e5-9da2-e9930cfca61d.jpeg)

**Comment by tarekp** [comment]
@hkrishna - We could autopopulate "Enter Zip" or just say "Search by Zipcode" for now...

**Comment by i8ramin** [comment]
I think the current implementation is good for launch. Says search by daycare or zipcode.
